### ISSUE TITLE
Cannot render forms when description=u'some description', even if description is ascii

### ISSUE THREAD

**Issue by dholth** [Pylons/pyramid_formish#1]
Due to formish RenderableObjectWrapper shenanigans?

The solution is to put this in pyramid_formish/templates/zpt/formish/field/main.html
-  <span tal:condition="str(field.description) != ''">${field.description}</span>
-  <span tal:condition="unicode(field.description) != ''">${unicode(field.description)}</span>

**Comment by mcdonc** [comment]
I believe this is fixed.  Can you review https://github.com/Pylons/pyramid_formish/blob/master/pyramid_formish/templates/zpt/formish/field/main.html and let me know.

**Comment by mcdonc** [comment]
Daniel approves.

**Comment by dholth** [comment]
import formish, schemaish

def test_unicode_description():
    schema = schemaish.Structure()
    schema.add('field', schemaish.String(description=u'unicode'))
    form = formish.Form(schema, name='test_unicode_description')
    form()

**Comment by mcdonc** [comment]
What is this issue suggesting?

**Comment by dholth** [comment]
That is just a unit test for the original bug, that you fixed.
