### ISSUE TITLE
Untitled

### ISSUE THREAD

**Issue by dholth** [Pylons/pyramid_formish#3]
Patch:
    diff --git a/setup.cfg b/setup.cfg
    index 8329597..5c81e59 100644
    --- a/setup.cfg
    +++ b/setup.cfg
    @@ -2,7 +2,7 @@
    zip_ok = false

```
 [nosetests]
-where=repoze/bfg/formish
+where=pyramid_formish
 match=^test
 nocapture=1
 cover-package=repoze.bfg.formish
```

**Comment by mcdonc** [comment]
This was already fixed on the trunk.
